const stateSegments = [
  { label: 'Hand', dim: 54, color: '#7c6cf0' },
  { label: 'Wild', dim: 12, color: '#b0a6ff' },
  { label: 'Others', dim: 54, color: '#4da6ff' },
  { label: 'Last', dim: 54, color: '#00e0a8' },
  { label: 'Team', dim: 54, color: '#00c090' },
  { label: 'Down', dim: 54, color: '#ff6b6b' },
  { label: 'Mate', dim: 54, color: '#ff9f43' },
  { label: 'Up', dim: 54, color: '#ffd93d' },
  { label: '#D', dim: 28, color: '#ff6b6b80' },
  { label: '#M', dim: 28, color: '#ff9f4380' },
  { label: '#U', dim: 28, color: '#ffd93d80' },
  { label: 'SR', dim: 13, color: '#4da6ff80' },
  { label: 'OR', dim: 13, color: '#4da6ff60' },
  { label: 'CR', dim: 13, color: '#4da6ff40' },
]
const totalDim = stateSegments.reduce((s, seg) => s + seg.dim, 0)

const nnLayers = [
  { size: 624, label: 'Input', color: '#4da6ff' },
  { size: 512, label: '512', color: '#7c6cf0' },
  { size: 512, label: '512', color: '#7c6cf0' },
  { size: 512, label: '512', color: '#7c6cf0' },
  { size: 512, label: '512', color: '#7c6cf0' },
  { size: 256, label: '256', color: '#b0a6ff' },
]

const rewardData = [
  { pattern: '1100', meaning: 'Both finish 1st & 2nd', reward: '+3', label: 'Sweep', color: '#00e0a8' },
  { pattern: '1010', meaning: 'Finish 1st & 3rd', reward: '+2', label: 'Good Win', color: '#4da6ff' },
  { pattern: '1001', meaning: 'Finish 1st & 4th', reward: '+1', label: 'Close Win', color: '#b0a6ff' },
  { pattern: '0110', meaning: 'Opponent 1st, us 2nd & 3rd', reward: '-1', label: 'Narrow Loss', color: '#ffd93d' },
  { pattern: '0101', meaning: 'Opponent stronger', reward: '-2', label: 'Loss', color: '#ff9f43' },
  { pattern: '0011', meaning: 'Opponent sweeps', reward: '-3', label: 'Crushed', color: '#ff6b6b' },
]

export default function Architecture() {
  return (
    <section className="section">
      <h2 className="section-title"><span className="icon">&#x1F9E0;</span> DanZero+ Core Architecture</h2>
      <p className="section-sub">Two-stage hybrid DQN + PPO decision system</p>

      {/* Two-Stage Pipeline */}
      <div className="arch-diagram">
        <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 24, fontWeight: 600, letterSpacing: 1, textTransform: 'uppercase' }}>
          Two-Stage Decision Pipeline
        </div>
        <div className="arch-flow">
          <div className="arch-stage env">
            <h4 style={{ color: '#00e0a8' }}>Legal Actions</h4>
            <p>N possible plays</p>
            <p style={{ fontSize: 11 }}>(generated by game engine)</p>
          </div>
          <div className="arch-arrow">&#x2192;</div>
          <div className="arch-stage dqn">
            <h4 style={{ color: '#4da6ff' }}>Stage 1: DQN</h4>
            <p>Score all N actions</p>
            <p style={{ fontWeight: 700, color: '#4da6ff', marginTop: 4 }}>Select Top-2</p>
            <div className="arch-label">Pretrained & Frozen</div>
          </div>
          <div className="arch-arrow">&#x2192;</div>
          <div className="arch-stage ppo">
            <h4 style={{ color: '#b0a6ff' }}>Stage 2: PPO</h4>
            <p>Choose 1 of 2</p>
            <p style={{ fontWeight: 700, color: '#b0a6ff', marginTop: 4 }}>Final Decision</p>
            <div className="arch-label">Online Training</div>
          </div>
          <div className="arch-arrow">&#x2192;</div>
          <div className="arch-stage env">
            <h4 style={{ color: '#00e0a8' }}>Play Card</h4>
            <p>Execute action</p>
          </div>
        </div>
        <p style={{ color: 'var(--text-muted)', fontSize: 13, marginTop: 16 }}>
          Like a multiple-choice exam: DQN eliminates wrong answers, PPO picks the best from remaining options
        </p>
      </div>

      {/* Neural Network */}
      <div style={{ marginTop: 40 }}>
        <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16 }}>Neural Network Architecture</h3>
        <div className="card-grid card-grid-2">
          <div className="card">
            <h4 style={{ color: '#b0a6ff', marginBottom: 12 }}>PPO Actor-Critic (MLPActorCritic)</h4>
            <div className="nn-diagram">
              {nnLayers.map((l, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center' }}>
                  <div className="nn-layer">
                    <div className="nn-block" style={{ background: l.color, height: Math.max(30, l.size / 10) }}>
                      {l.label}
                    </div>
                    {i === 0 && <div className="nn-label">State+Act</div>}
                    {i === nnLayers.length - 1 && <div className="nn-label">Shared</div>}
                  </div>
                  {i < nnLayers.length - 1 && <span className="nn-connector">&#x2192;</span>}
                </div>
              ))}
              <span className="nn-connector">&#x2192;</span>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                <div className="nn-layer">
                  <div className="nn-block" style={{ background: '#00e0a8', height: 30, width: 64, fontSize: 10 }}>Policy &#x3C0;</div>
                  <div className="nn-label">128&#x2192;2</div>
                </div>
                <div className="nn-layer">
                  <div className="nn-block" style={{ background: '#ff9f43', height: 30, width: 64, fontSize: 10 }}>Value V</div>
                  <div className="nn-label">128&#x2192;1</div>
                </div>
              </div>
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', textAlign: 'center', marginTop: 8 }}>
              5 hidden layers (Tanh) + orthogonal init | 1.3M params
            </div>
          </div>

          <div className="card">
            <h4 style={{ color: '#4da6ff', marginBottom: 12 }}>DQN Q-Network (MLPQNetwork)</h4>
            <div className="nn-diagram">
              {[
                { size: 567, label: '567', color: '#4da6ff' },
                { size: 512, label: '512', color: '#2a7ad4' },
                { size: 512, label: '512', color: '#2a7ad4' },
                { size: 512, label: '512', color: '#2a7ad4' },
                { size: 512, label: '512', color: '#2a7ad4' },
                { size: 512, label: '512', color: '#2a7ad4' },
                { size: 1, label: 'Q', color: '#ff6b6b' },
              ].map((l, i, arr) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center' }}>
                  <div className="nn-layer">
                    <div className="nn-block" style={{ background: l.color, height: Math.max(24, l.size / 10) }}>
                      {l.label}
                    </div>
                    {i === 0 && <div className="nn-label">State+Act</div>}
                    {i === arr.length - 1 && <div className="nn-label">Score</div>}
                  </div>
                  {i < arr.length - 1 && <span className="nn-connector">&#x2192;</span>}
                </div>
              ))}
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', textAlign: 'center', marginTop: 8 }}>
              5 hidden layers (Tanh) | 1.34M params | Pretrained via Deep Monte Carlo
            </div>
          </div>
        </div>
      </div>

      {/* State Representation */}
      <div style={{ marginTop: 40 }}>
        <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16 }}>State Representation ({totalDim}+3 = 516 dims)</h3>
        <div className="card">
          <div className="state-bar">
            {stateSegments.map((seg, i) => (
              <div
                key={i}
                className="state-segment"
                style={{ flex: seg.dim, background: seg.color, borderRight: '1px solid var(--bg)' }}
                title={`${seg.label}: ${seg.dim} dims`}
              >
                {seg.dim >= 28 ? `${seg.label} (${seg.dim})` : seg.dim >= 13 ? seg.dim : ''}
              </div>
            ))}
          </div>
          <div className="table-wrap" style={{ marginTop: 16 }}>
            <table>
              <thead>
                <tr><th>Feature</th><th>Dims</th><th>Description</th><th>Encoding</th></tr>
              </thead>
              <tbody>
                {[
                  ['my_handcards', '54', 'Own hand cards', 'Count per card (0/1/2)'],
                  ['universal_card_flag', '12', 'Wildcard ability flags', '12-bit binary'],
                  ['other_handcards', '54', 'All opponents remaining cards', 'Count per card'],
                  ['last_action', '54', 'Latest play on table', 'Card encoding'],
                  ['last_teammate_action', '54', "Teammate's last play", 'Card encoding'],
                  ['down/mate/up_played', '54x3', 'Each player played history', 'Card encoding'],
                  ['down/mate/up_num_left', '28x3', 'Cards remaining per player', 'One-hot (0-27)'],
                  ['self/oppo/cur_rank', '13x3', 'Team levels & current rank', 'One-hot (2-A)'],
                ].map((row, i) => (
                  <tr key={i}>
                    <td style={{ fontFamily: 'JetBrains Mono', fontSize: 12, color: 'var(--accent-light)' }}>{row[0]}</td>
                    <td style={{ fontWeight: 700 }}>{row[1]}</td>
                    <td>{row[2]}</td>
                    <td style={{ fontSize: 12 }}>{row[3]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Reward Function */}
      <div style={{ marginTop: 40 }}>
        <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16 }}>Reward Function</h3>
        <div className="card-grid card-grid-3">
          {rewardData.map(r => (
            <div className="card" key={r.pattern} style={{ textAlign: 'center', borderTop: `3px solid ${r.color}` }}>
              <div style={{ fontFamily: 'JetBrains Mono', fontSize: 28, fontWeight: 800, color: r.color, marginBottom: 4 }}>
                {r.pattern}
              </div>
              <div style={{ fontSize: 32, fontWeight: 900, color: r.color }}>{r.reward}</div>
              <div style={{ fontSize: 14, fontWeight: 600, marginTop: 4 }}>{r.label}</div>
              <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 4 }}>{r.meaning}</div>
            </div>
          ))}
        </div>
        <p style={{ color: 'var(--text-muted)', fontSize: 13, marginTop: 12 }}>
          Pattern: "1" = our team player, "0" = opponent. Order = finish position. Extra &#xB1;1 bonus at rank A (finals).
        </p>
      </div>

      {/* PPO Training */}
      <div style={{ marginTop: 40 }}>
        <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16 }}>PPO Training Loop</h3>
        <div className="card">
          <div className="code-block">
            <pre>{`# Total Loss = policy_loss + 0.5 * value_loss + 0.05 * entropy_loss

for iter in range(20):                    # max 20 gradient steps
    ratio = exp(log_prob - log_prob_old)  # importance sampling
    clipped = clamp(ratio, 0.8, 1.2)     # PPO clip

    loss_pi  = -min(ratio * adv, clipped * adv)   # policy loss
    loss_v   = 0.5 * (V(s) - Return)^2            # value loss
    loss_ent = -entropy(pi)                        # entropy bonus

    loss = loss_pi + 0.5 * loss_v + 0.05 * loss_ent
    loss.backward()
    clip_grad_norm(params, max_norm=10)
    optimizer.step()                      # Adam, lr=1e-4

    if KL_divergence > 0.015:             # early stopping
        break`}</pre>
          </div>
          <div className="card-grid card-grid-3" style={{ marginTop: 20 }}>
            {[
              { name: 'Policy Loss', desc: 'Make good plays more likely, limit update magnitude', color: '#7c6cf0' },
              { name: 'Value Loss', desc: 'Predict how good current position is (MSE)', color: '#ff9f43' },
              { name: 'Entropy Loss', desc: 'Encourage exploration, prevent premature convergence', color: '#00e0a8' },
            ].map(l => (
              <div key={l.name} style={{ padding: 16, background: 'var(--bg)', borderRadius: 8, borderLeft: `3px solid ${l.color}` }}>
                <div style={{ fontWeight: 700, fontSize: 14, color: l.color }}>{l.name}</div>
                <div style={{ fontSize: 12, color: 'var(--text-dim)', marginTop: 4 }}>{l.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* GAE */}
      <div style={{ marginTop: 40 }}>
        <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16 }}>GAE (Generalized Advantage Estimation)</h3>
        <div className="card-grid card-grid-2">
          <div className="card">
            <div className="code-block">
              <pre>{`gamma = 0.99   # discount factor
lam   = 0.95   # GAE lambda

# TD residuals
delta_t = r_t + gamma * V(s_{t+1}) - V(s_t)

# Backward accumulation
A_t = delta_t + gamma * lam * A_{t+1}

# Returns for value training
Return_t = A_t + V(s_t)`}</pre>
            </div>
          </div>
          <div className="card">
            <h4 style={{ marginBottom: 12 }}>Key Hyperparameters</h4>
            <div className="table-wrap">
              <table>
                <tbody>
                  {[
                    ['gamma', '0.99', 'Long-term vision (a GuanDan game has 50-100 steps)'],
                    ['lambda', '0.95', 'Bias-variance tradeoff for advantage estimation'],
                    ['clip_ratio', '0.2', 'PPO clipping range [0.8, 1.2]'],
                    ['lr', '1e-4', 'Adam optimizer learning rate'],
                    ['train_iters', '20', 'Max gradient steps per batch'],
                    ['target_kl', '0.01', 'KL divergence limit for early stopping'],
                    ['batch_size', '2048', 'Training batch size'],
                    ['training_freq', '13', 'Train once per 13 data receptions'],
                  ].map(([k, v, d]) => (
                    <tr key={k}>
                      <td style={{ fontFamily: 'JetBrains Mono', color: 'var(--accent-light)', fontSize: 12 }}>{k}</td>
                      <td style={{ fontWeight: 700 }}>{v}</td>
                      <td style={{ fontSize: 12 }}>{d}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
